/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./src/**/*.{html,ts}",
  ],
 darkMode: "class",
                theme: {
                    extend: {
                        colors: {
                            "inverse-on-surface": "#283044",
                            "on-primary-fixed": "#00174b",
                            "on-tertiary-container": "#c1ffc5",
                            "tertiary": "#4ae176",
                            "on-secondary-container": "#aeb9d0",
                            "surface-tint": "#b4c5ff",
                            "surface-container-high": "#222a3d",
                            "tertiary-fixed": "#6bff8f",
                            "inverse-surface": "#dae2fd",
                            "inverse-primary": "#0053db",
                            "secondary": "#053295",
                            "outline-variant": "#434655",
                            "on-surface": "#dae2fd",
                            "on-surface-variant": "#c3c6d7",
                            "primary-container": "#2563eb",
                            "primary-fixed": "#dbe1ff",
                            "tertiary-container": "#007e37",
                            "on-secondary-fixed": "#111c2d",
                            "error": "#ffb4ab",
                            "on-background": "#dae2fd",
                            "surface-bright": "#31394d",
                            "outline": "#8d90a0",
                            "on-tertiary-fixed-variant": "#005321",
                            "background": "#0b1326",
                            "primary": "#b4c5ff",
                            "surface-variant": "#2d3449",
                            "on-primary-fixed-variant": "#003ea8",
                            "on-tertiary-fixed": "#002109",
                            "on-secondary": "#263143",
                            "on-primary-container": "#eeefff",
                            "on-tertiary": "#003915",
                            "primary-fixed-dim": "#b4c5ff",
                            "surface-dim": "#0b1326",
                            "on-error-container": "#ffdad6",
                            "surface-container-highest": "#2d3449",
                            "on-error": "#690005",
                            "secondary-fixed": "#d8e3fb",
                            "on-primary": "#002a78",
                            "surface": "#0b1326",
                            "surface-container-lowest": "#060e20",
                            "on-secondary-fixed-variant": "#3c475a",
                            "tertiary-fixed-dim": "#4ae176",
                            "secondary-container": "#3e495d",
                            "secondary-fixed-dim": "#bcc7de",
                            "surface-container": "#171f33",
                            "error-container": "#93000a",
                            "surface-container-low": "#131b2e"
                        },
                        fontFamily: {
                            "headline": ["Inter", "sans-serif"],
                            "body": ["Inter", "sans-serif"],
                            "label": ["Inter", "sans-serif"]
                        },
                        borderRadius: {
                            "DEFAULT": "0.25rem",
                            "lg": "0.5rem",
                            "xl": "0.75rem",
                            "2xl": "1rem",
                            "3xl": "2rem",
                            "full": "9999px"
                        },
                    },
                },
  plugins: [],
}